language: python
cache:
  directories:
  - $HOME/virtualenv
services:
- postgresql
python:
- 2.7
- 3.4
install:
- pip install -r requirements/minimal.txt
- pip install -r requirements/postgres.txt
- pip install -r requirements/test.txt
- pip install coveralls
before_script:
- cp DMPwerkzeug/settings/travis.py DMPwerkzeug/settings/local.py
script:
- coverage run manage.py test
after_success:
- coveralls
